document:
  name: api-gateway

spring:
  cloud:
    gateway:
      routes:
#        - id: document-service-route #убрал, что бы публичным не делать
#          uri: lb://document-service
#          predicates:
#            - Path=/api/documents/**
#        - id: auth-service-route
#          uri: lb://auth-service
#          predicates:
#            - Path=/api/auth/**
        - id: portal-service-route
          uri: lb://portal-service
          predicates:
            - Path=/web/portal/**
