document:
  name: api-gateway

spring:
  cloud:
    gateway:
      routes:
        - id: document-service-route
          uri: lb://document-service
          predicates:
            - Path=/api/documents/**
        - id: portal-service-route
          uri: lb://portal-service
          predicates:
            - Path=/api/portal/**
