eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

---

spring:
  cloud:
    loadbalancer:
      ribbon:
        eureka:
          enabled: true
    ribbon:
      eureka:
        enabled: true
      ServerListRefreshInterval: 1000
      ReadTimeout: 3000
      ConnectTimeout: 5000
      MaxAutoRetries: 0
      MaxAutoRetriesNextServer: 1